### ISSUE TITLE
Consider using UUID instead of String in PNCounter codec template

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast-client-protocol#119]
In `PNCounterGeneratorCodecTemplate` a `List<Entry<String, Long>> replicaTimestamps` is used as replica ID -> vector clock value. Since [replica IDs are `UUID`s](https://github.com/hazelcast/hazelcast/blob/e0ea8ed98b3c30d4e8a03d38fc6fd9c6bca57574/hazelcast/src/main/java/com/hazelcast/crdt/pncounter/PNCounterService.java#L70) and client protocol already includes a UUID codec, we could use `List<Entry<UUID, Long>>` instead and shave off some bytes /cc @mmedenjak ?

**Comment by asimarslan** [comment]
fixed with #214
