### ISSUE TITLE
No longer able to compile version 1.0.0

### ISSUE THREAD

**Issue by lukasblu** [hazelcast/hazelcast-client-protocol#18]
Hi,

when I try to compile version 1.0.0 of the client protocol (to use it with Hazelcast version 3.6), the build fails.

Here are my steps:
$ git clone https://github.com/hazelcast/hazelcast-client-protocol.git hazelcast-client-protocol
$ cd hazelcast-client-protocol/
$ git checkout release
$ mvn clean compile

and the error I get is:

[INFO] ------------------------------------------------------------------------
[INFO] Building hazelcast-client-protocol 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hazelcast-client-protocol ---
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:exec (Clean Downloaded Hazelcast Zip) @ hazelcast-client-protocol ---
rm: cannot remove 'removeCodeGeneratorModule.zip*': No such file or directory
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:exec (Download Hazelcast Zip) @ hazelcast-client-protocol ---
unzip:  cannot find or open removeCodeGeneratorModule.zip, removeCodeGeneratorModule.zip.zip or removeCodeGeneratorModule.zip.ZIP.
cp: cannot stat './hazelcast-removeCodeGeneratorModule/hazelcast/src/main': No such file or directory

could the build be fixed such that version 1.0.0 can be built again?

Thanks and best,
Lukas

**Comment by asimarslan** [comment]
already fixed
